---
- name: sysctl --system
  shell: sysctl --system

- name: Test AWS CLI
  shell: aws --profile {{ item }} ec2 describe-availability-zones
  with_items:
  - hit
  - crisp
  - codekvast

- name: systemctl daemon-reload
  shell: systemctl daemon-reload

- name: systemctl restart network-manager
  shell: systemctl restart network-manager

- name: Relogin needed
  debug: msg='You need to logout and login'
