---
- name: Create /usr/share/ca-certificates/{{ secrets.customer3.name }}/
  file: path=/usr/share/ca-certificates/{{ secrets.customer3.name }} state=directory

- name: Install /usr/share/ca-certificates/{{ secrets.customer3.name }}/{{ secrets.customer3.name }}_ca.crt
  copy:
    src: customer3/web-ca.crt
    dest: /usr/share/ca-certificates/{{ secrets.customer3.name }}/{{ secrets.customer3.name }}_ca.crt
    owner: root
    group: root
    mode: 0644
  notify: update-ca-certificates
