---
- name: Remove /usr/share/ca-certificates/{{ secrets.customer3.name }}
  file: path=/usr/share/ca-certificates/{{ secrets.customer3.name }} state=absent
  notify: update-ca-certificates

- name: Create /usr/local/share/ca-certificates/
  file: path=/usr/local/share/ca-certificates state=directory

- name: Install /usr/local/share/ca-certificates/{{ secrets.customer3.name }}_ca.crt
  copy:
    src: customer3/web-ca.crt
    dest: /usr/local/share/ca-certificates/{{ secrets.customer3.name }}_ca.crt
    owner: root
    group: root
    mode: 0644
  notify: update-ca-certificates

- name: Install various utilities
  package: name={{ item }} state=present
  with_items:
  - postgresql-client
  - python3-pip

- name: Install kubectl
  command: snap install kubectl --classic
  args:
    creates: /snap/bin/kubectl

- name: Create $HOME/.kube
  file:
    path: "{{ lookup('env', 'HOME')}}/.kube"
    state: directory
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0755

- name: Create Create $HOME/.kube/config
  copy:
    src: customer3/kube-config
    dest: "{{ lookup('env', 'HOME')}}/.kube/config"

- name: Install aws-adfs-tool
  shell: pip3 install files/customer3/aws_adfs_tool-2.4.6.tar.gz
  args:
    creates: "{{ lookup('env', 'HOME')}}/.local/bin/aws-adfs-tool"
  become_user: "{{ actual_username }}"

- name: Install postman
  command: snap install postman
  args:
    creates: /snap/bin/postman

