- name: Install AWS CLI
  package: name={{ item }} state=present
  with_items:
  - awscli

- name: Create AWS config directory
  file: path=/home/{{ actual_username }}/.aws state=directory owner={{ actual_username }} group={{ actual_username }} mode=0755

- name: Configure AWS CLI
  ini_file: dest=/home/{{ actual_username }}/.aws/config owner={{ actual_username }} group={{ actual_username }} mode=0644 section={{ item.s }}  option={{ item.k }} value={{ item.v }}
  with_items:
  - { s: 'profile hit', k: region, v: eu-west-1 }
  - { s: 'profile crisp', k: region, v: eu-central-1 }
