- name: Install AWS CLI
  package: name={{ item }} state=present
  with_items:
  - awscli
  tags:
  - aws

- name: Create AWS config directory
  file: path=/home/olle/.aws state=directory owner=olle group=olle mode=0755
  tags:
  - aws

- name: Configure AWS CLI
  ini_file: dest=/home/olle/.aws/config owner=olle group=olle mode=0644 section={{ item.s }}  option={{ item.k }} value={{ item.v }}
  with_items:
  - { s: 'profile hit', k: region, v: eu-west-1 }
  - { s: 'profile crisp', k: region, v: eu-central-1 }
  tags:
  - aws
