---
- name: Install OpenJDK
  package: name={{ item }} state=present
  with_items:
  - openjdk-8-jdk
  - openjdk-8-source
  - openjdk-8-doc

- name: Install git and curl
  package: name={{ item }} state=present
  with_items:
  - git
  - curl

- name: Uninstall nodejs-legacy
  package: name=nodejs-legacy state=absent

- name: Define NodeJS APT source
  shell: curl -sL https://deb.nodesource.com/setup_6.x | bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: Install NodeJS
  package: name={{ item }} state=latest
  with_items:
  - nodejs
  - build-essential

- name: Install PhantomJS
  npm: name=phantomjs-prebuilt global=yes

- name: Install gradlew finder
  template: src=gradlew-finder.sh dest=/usr/local/bin/gradle mode=a=rx
