---
- name: Install OpenJDK
  package: name={{ item }} state=present
  with_items:
  - openjdk-8-jdk
  - openjdk-8-source
  - openjdk-8-doc

- name: Install Node and NPM
  package: name={{ item }} state=present
  with_items:
  - npm
  - nodejs-legacy

- name: Install gradlew finder
  template: src=gradlew-finder.sh dest=/usr/local/bin/gradle mode=a=rx
