---
- name: Install OpenJDK 8
  package: name={{ item }} state=present
  with_items:
  - openjdk-8-jdk
  - openjdk-8-source
  - openjdk-8-doc

- name: Uninstall OpenJDK 11
  package: name={{ item }} state=absent
  with_items:
  - openjdk-11-jdk
  - openjdk-11-jdk-headless
  - openjdk-11-jre
  - openjdk-11-jre-headless
  - openjdk-11-source
  - openjdk-11-doc

- name: Install git and curl
  package: name={{ item }} state=present
  with_items:
  - git
  - curl

- name: Uninstall nodejs-legacy
  package: name=nodejs-legacy state=absent

- name: Fetch NodeJS APT source script
  get_url: url=https://deb.nodesource.com/setup_8.x dest=/tmp/nodesource_apt_source.sh mode=0755

- name: Execute NodeJS APT source script
  shell: /tmp/nodesource_apt_source.sh # creates=/etc/apt/sources.list.d/nodesource.list

- name: Install NodeJS
  package: name={{ item }} state=latest
  with_items:
  - nodejs
  - build-essential

- name: Remove phantomjs-prebuilt from /usr/local
  file: path={{ item }} state=absent
  with_items:
  - /usr/local/lib/node_modules/phantomjs-prebuilt
  - /usr/local/bin/phantomjs

- name: Install gradlew finder
  template: src=gradlew-finder.sh dest=/usr/local/bin/gradle mode=a=rx
