---
- set_fact: sdkman_dir={{ lookup('env', 'HOME')}}/.sdkman fish_config_dir={{ lookup('env', 'HOME')}}/.config/fish

- name: Get SDKMAN installer
  get_url: url=https://get.sdkman.io dest=/tmp/sdkman-installer.sh mode=0755

- name: Execute SDKMAN installer
  shell: /tmp/sdkman-installer.sh creates="{{ sdkman_dir }}"

- name: chown $HOME/.sdkman
  file: path={{ sdkman_dir }} owner={{ actual_username }} recurse=yes

- name: chmod +x $HOME/.sdkman/bin
  file: path={{ sdkman_dir }}/bin mode=0755 recurse=yes

- name: Install fish
  package: name=fish state=present

- name: Set Fish as login shell
  user: name={{ actual_username }} shell=/usr/bin/fish

- name: Create Fish config directories
  file: dest={{ fish_config_dir }}/{{ item }} state=directory
  with_items:
  - functions
  - completions

- name: Install Fish SDKMAN support
  copy:
    src: files/fish/{{ item }}
    dest: "{{ fish_config_dir }}/{{ item }}"
  with_items:
  - completions/docker.fish
  - completions/sdk.fish
  - functions/fish_prompt.fish
  - functions/mkd.fish
  - functions/sdk.fish

- name: Set correct ownership of {{ fish_config_dir }}
  file: dest={{ fish_config_dir }} owner={{ actual_username }} group={{ actual_username }} recurse=yes
