---
- name: Set root as owner to ~/.netrc
  file: path=~/.netrc state=touch owner=root
  changed_when: False

- name: Install Heroku APT key
  apt_key: url=https://cli-assets.heroku.com/apt/release.key state=present

- name: Make sure Heroku APT source is defined
  apt_repository:
    filename: heroku
    repo: "deb https://cli-assets.heroku.com/branches/stable/apt ./"
    state: present

- name: Install Heroku Toolbelt
  package: name=heroku state=present

- name: Reset ownership and mode of ~/.netrc
  file: path=~/.netrc owner={{ actual_username }} group={{ actual_username }} mode=0600
  changed_when: False

