---
- name: Download /tmp/{{ intellij_archive }}
  get_url:
    url: https://download.jetbrains.com/idea/{{ intellij_archive }}
    checksum: "{{ intellij_checksum }}"
    dest: /tmp/{{ intellij_archive }}

- name: Unpack /tmp/{{ intellij_archive }} into /opt/idea-IU-{{ intellij_version }}
  unarchive:
    src: /tmp/{{ intellij_archive }}
    copy: no
    dest: /opt/
    creates: /opt/idea-IU-{{ intellij_version }}

- name: Create symlink /opt/idea -> /opt/idea-IU-{{ intellij_version }} for convenience
  file: src=/opt/idea-IU-{{ intellij_version }} dest=/opt/idea state=link

- name: Create /usr/share/applications/jetbrains-idea.desktop
  template:
    src: templates/jetbrains-idea.desktop
    dest: /usr/share/applications/jetbrains-idea.desktop
    mode: 0755

- name: Increase inotify watch limit
  template: src=60-jetbrains.conf dest=/etc/sysctl.d/60-jetbrains.conf
  notify: sysctl --system
