---
- name: Ensure /home/{{ actual_username }}/{{ item }} exists
  file: path=/home/{{ actual_username }}/{{ item }} state=directory owner={{ actual_username }} group={{ actual_username }}
  with_items:
  - apps
  - "H채mtningar"

- set_fact: intellij_archive=ideaIU-{{ intellij_version }}{{ intellij_download_classifier }}.tar.gz

- name: Download {{ intellij_archive }} into /home/{{ actual_username }}/H채mtningar
  get_url:
    url: https://download.jetbrains.com/idea/{{ intellij_archive }}
    checksum: "{{ intellij_checksum }}"
    dest: /home/{{ actual_username }}/H채mtningar/{{ intellij_archive }}
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"

- name: Unpack {{ intellij_archive }} into /home/{{ actual_username }}/apps/
  unarchive:
    src: /home/{{ actual_username }}/H채mtningar/{{ intellij_archive }}
    copy: no
    dest: /home/{{ actual_username }}/apps/
    creates: /home/{{ actual_username }}/apps/idea-IU-{{ intellij_version }}

- name: Set correct ownership of files
  file:
    path: /home/{{ actual_username }}/apps/idea-IU-{{ intellij_version }}
    recurse: yes
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    
- name: Install desktop files
  template:
    src: templates/jetbrains-idea.desktop
    dest: /home/{{ actual_username }}/.local/share/applications/jetbrains-idea.desktop
    mode: 0755
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"

- name: Create symlink for convenience
  file:
    src: /home/{{ actual_username }}/apps/idea-IU-{{ intellij_version }}
    dest: /home/{{ actual_username }}/apps/idea
    state: link
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
