---
- name: Install Fish
  package: name=fish state=present
  tags:
  - shell
  - fish

- name: Get the current login shell
  set_fact:
  args:
    current_login_shell: "{{ lookup('csvfile',  lookup('env', 'USER') + ' file=\"/etc/passwd\" delimiter=: col=6') }}"
  tags:
  - shell
  - fish
  
- name: Set Fish as login shell
  when:  "{{ current_login_shell != '/usr/bin/fish' }}"
  shell: chsh --shell /usr/bin/fish {{ lookup('env', 'USER') }}
  tags:
  - shell
  - fish

- name: Install Emacs
  package: name=emacs24 state=present
  tags:
  - editor
  - emacs
