---
- name: Install misc utilities
  package: name={{ item }} state=present
  with_items:
  - ack
  - compizconfig-settings-manager
  - curl
  - dconf-cli
  - emacs24
  - indicator-cpufreq
  - jq
  - keepassx
  - libimage-exiftool-perl
  - nautilus-dropbox
  - openssh-server
  - slack-desktop
  - synaptic
  - unzip
  - wget

- name: Start sshd
  service: name=sshd state=started enabled=yes

- name: Create $HOME/bin
  file:
    dest: "{{ lookup('env', 'HOME')}}/bin"
    state: directory
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0755

- name: Create $HOME/.gradle
  file: path={{ lookup('env', 'HOME') }}/.gradle state=directory owner={{ actual_username }} group={{ actual_username }} mode=755

- name: Edit $HOME/.gradle/gradle.properties
  blockinfile:
    dest: "{{ lookup('env', 'HOME') }}/.gradle/gradle.properties"
    create: yes
    backup: yes
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0600
    block: |
      bintrayUser={{ secrets.bintray.user }}
      bintrayKey={{ secrets.bintray.key }}
