---
- name: Install misc utilities
  package: name={{ item }} state=present
  with_items:
  - compizconfig-settings-manager
  - curl
  - dconf-cli
  - emacs24
  - fish
  - indicator-cpufreq
  - jq
  - keepassx
  - nautilus-dropbox
  - synaptic
  - unzip
  - wget

- name: Set Fish as login shell
  user: name={{ actual_username }} shell=/usr/bin/fish
  tags:
  - shell
  - fish

- name: Create $HOME/bin
  file:
    dest: "{{ lookup('env', 'HOME')}}/bin"
    state: directory
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0755

