---
- name: "Install mkpasswd (and other stuff from the whois package)"
  package: name=whois state=present

- name: "Make the root password"
  shell: echo {{ secrets.root.password }} | mkpasswd --method=sha-512 --stdin
  register: p
  changed_when: false

- name: "Set the root password"
  user: name=root system=yes password="{{ p.stdout }}"
