---
- set_fact: sdkman_dir={{ lookup('env', 'HOME')}}/.sdkman

- name: Install SDKMAN
  shell: curl -s https://get.sdkman.io | bash
  args:
    creates: "{{ sdkman_dir }}"

- name: chown $HOME/.sdkman
  file: path={{ sdkman_dir}} owner={{ actual_username }} recurse=yes

- name: chmod +x $HOME/.sdkman/bin
  file: path={{ sdkman_dir}}/bin mode=0755 recurse=yes

- name: Execute sdkman-init.sh
  shell: "{{ sdkman_dir }}/bin/sdkman-init.sh"
