---

- name: Add APT key
  apt_key: id=BBEBDCB318AD50EC6865090613B00F1FD2C19886 keyserver=hkp://keyserver.ubuntu.com:80

- name: Add APT repository
  apt_repository: repo="deb http://repository.spotify.com stable non-free" filename=spotify.list

- name:
  package: name=spotify-client state=present
