---

- name: Add APT keys
  apt_key: id={{ item }} keyserver=hkp://keyserver.ubuntu.com:80
  with_items:
  - BBEBDCB318AD50EC6865090613B00F1FD2C19886
  - 0DF731E45CE24F27EEEB1450EFDC8610341D9410

- name: Add APT repository
  apt_repository: repo="deb http://repository.spotify.com stable non-free" filename=spotify.list

- name:
  package: name=spotify-client state=present
