---
  
- name: Install Vagrant and system-wide plugins
  package: name={{ item }} state=present
  with_items:
  - vagrant
  - vagrant-cachier

- name: Install user-specific Vagrant plugins
  command: vagrant plugin install {{ item }} creates="{{ lookup('env', 'HOME') }}/.vagrant.d/gems/specifications/{{ item }}-*.gemspec"
  with_items:
  - vagrant-hostmanager
  - vagrant-vbguest

- name: Set correct ownership of $HOME/{{ item }}/**
  file: dest={{ lookup('env', 'HOME') }}/{{ item }} owner={{ actual_username }} group={{ actual_username }} state=directory recurse=yes
  with_items:
  - .bundle
  - .vagrant.d
  - .gem

