---
- name: Install apache2
  package: name=apache2 state=installed

- name: Enable Apache modules
  apache2_module: name={{ item }} state=present
  with_items:
  - proxy
  - proxy_http
  notify: restart apache

- name: Install Apache proxy config
  template: src=templates/customer2/apache-proxy.conf dest=/etc/apache2/sites-available/{{ secrets.customer2.apache.siteName }}.conf
  notify: restart apache

- name: Enable Apache proxy config
  file:
    src: /etc/apache2/sites-available/{{ secrets.customer2.apache.siteName }}.conf
    dest: /etc/apache2/sites-enabled/{{ secrets.customer2.apache.siteName }}.conf
    state: link
  notify: restart apache

- name: Start Apache
  service: name=apache2 state=started
