---
- name: Install network-manager-openvpn-gnome
  package:
    name:
    - network-manager-openvpn-gnome
    - network-manager-openconnect-gnome
    state: present
  notify: systemctl daemon-reload

- debug: msg="Define the VPN to {{ secrets.customer2.name | capitalize }} by importing {{ pwd }}/files/customer2/heimdall.ovpn into Gnome Network Manager -> VPN"
