---
- hosts: all
  connection: local
  become: yes
  vars_files:
  - vars/secrets.yml

  handlers:
  - import_tasks: handlers/main.yml

  post_tasks:
  - {import_tasks: tasks/cisco-vpn-client.yml, tags: [vpn, vpnc]}
  - {import_tasks: tasks/hipchat.yml, tags: hipchat}
  - {import_tasks: tasks/erlang.yml, tags: erlang, distribution_release: xenial}
