---
- hosts: all
  connection: local
  become: yes
  vars:
  - docker_compose_version: 1.8.0
  - docker_machine_version: 0.7.0
  - intellij_version: 163.6110.12
  - intellij_checksum: "sha256:35614483efe45738da987c319e160eff4061a794f295f575b68207069f021eef"
  - intellij_download_classifier: "-no-jdk"

  handlers:
  - include: handlers/main.yml

  roles:
    - {role: franklinkim.docker, tags: [docker, docker-engine] }
  
  post_tasks:
  - {include: tasks/docker.yml, tags: docker}
  - {include: tasks/compilers.yml, tags: compilers}
  - {include: tasks/virtualbox.yml, tags: virtualbox}
  - {include: tasks/vagrant.yml, tags: vagrant}
  - {include: tasks/aws-cli.yml, tags: aws}
  - {include: tasks/misc.yml, tags: misc}
  - {include: tasks/intellij.yml, tags: intellij}
  - {include: tasks/spotify.yml, tags: spotify}
