---
- hosts: all
  connection: local
  become: yes
  vars:
  - docker_compose_version: 1.15.0
  - docker_machine_version: 0.12.2
  - intellij_version: 173.4127.2
  - intellij_checksum: "sha256:685861548eb5238ac65ba6ccc08d6951a9daa1cdc9a253a055f1a909d14bf7ae"
  - intellij_archive: ideaIU-{{ intellij_version }}-no-jdk.tar.gz
  vars_files:
  - vars/secrets.yml

  handlers:
  - include: handlers/main.yml

  roles:
  - {role: franklinkim.docker, tags: [docker, docker-engine], distribution_release: zesty}
  
  post_tasks:
  - {include: tasks/aws-cli.yml, tags: aws}
  - {include: tasks/calibre.yml, tags: calibre}
  - {include: tasks/charles-proxy.yml, tags: [charles-proxy, charles]}
  - {include: tasks/compilers.yml, tags: [compilers, codekvast]}
  - {include: tasks/docker.yml, tags: [docker, codekvast]}
  - {include: tasks/fish.yml, tags: [fish, sdkman]}
  - {include: tasks/google-chrome.yml, tags: [chrome, google-chrome]}
  - {include: tasks/heroku-toolbelt.yml, tags: [heroku, codekvast]}
  - {include: tasks/intellij.yml, tags: [intellij, idea, codekvast]}
  - {include: tasks/misc.yml, tags: misc}
  - {include: tasks/nfs-mounts.yml, tags: [fstab, nfs, nfs-mounts]}
  - {include: tasks/scala.yml, tags: [compilers, scala]}
  - {include: tasks/spotify.yml, tags: spotify}
  - {include: tasks/vagrant.yml, tags: vagrant}
  - {include: tasks/virtualbox.yml, tags: virtualbox}
  - {include: tasks/yarn.yml, tags: yarn}
