---
- hosts: all
  connection: local
  become: yes
  vars:
  - docker_compose_version: 1.9.0
  - docker_machine_version: 0.8.2
  - intellij_version: 171.1834.9
  - intellij_checksum: "sha256:450636fbda057b3236ec0aea4b2d1acac2d183dd2ef539afcc03047f1d2557d0"
  - intellij_archive: ideaIU-171.1834.9-no-jdk.tar.gz

  vars_files:
  - vars/secrets.yml

  handlers:
  - include: handlers/main.yml

  roles:
  - {role: franklinkim.docker, tags: [docker, docker-engine]}
  
  post_tasks:
  - {include: tasks/docker.yml, tags: [docker, codekvast]}
  - {include: tasks/calibre.yml, tags: calibre}
  - {include: tasks/compilers.yml, tags: [compilers, codekvast]}
  - {include: tasks/virtualbox.yml, tags: virtualbox}
  - {include: tasks/vagrant.yml, tags: vagrant}
  - {include: tasks/aws-cli.yml, tags: aws}
  - {include: tasks/fish.yml, tags: [fish, sdkman]}
  - {include: tasks/misc.yml, tags: misc}
  - {include: tasks/intellij.yml, tags: [intellij, codekvast]}
  - {include: tasks/nfs-mounts.yml, tags: [fstab, nfs, nfs-mounts]}
