---
- hosts: all
  connection: local
  become: yes
  vars:
  - docker_compose_version: 1.15.0
  - docker_machine_version: 0.12.2
  - intellij_version: 181.4892.5
  - intellij_checksum: "sha256:c3bf065f39072e7ddd81855ff93fabda68997248f9feaef25a54f45e9582afae"
  - intellij_archive: ideaIU-{{ intellij_version }}-no-jdk.tar.gz
  vars_files:
  - vars/secrets.yml

  handlers:
  - import_tasks: handlers/main.yml

  roles:
  - {role: franklinkim.docker, tags: [docker, docker-engine], distribution_release: zesty}
  
  post_tasks:
  - {import_tasks: tasks/aws-cli.yml, tags: aws}
  - {import_tasks: tasks/calibre.yml, tags: calibre}
  - {import_tasks: tasks/charles-proxy.yml, tags: [charles-proxy, charles]}
  - {import_tasks: tasks/compilers.yml, tags: [compilers, codekvast]}
  - {import_tasks: tasks/docker.yml, tags: [docker, codekvast]}
  - {import_tasks: tasks/fish.yml, tags: [fish, sdkman]}
  - {import_tasks: tasks/google-chrome.yml, tags: [chrome, google-chrome]}
  - {import_tasks: tasks/heroku-toolbelt.yml, tags: [heroku, codekvast]}
  - {import_tasks: tasks/intellij.yml, tags: [intellij, idea, codekvast]}
  - {import_tasks: tasks/misc.yml, tags: misc}
  - {import_tasks: tasks/nfs-mounts.yml, tags: [fstab, nfs, nfs-mounts]}
  - {import_tasks: tasks/scala.yml, tags: [compilers, scala]}
  - {import_tasks: tasks/spotify.yml, tags: spotify}
  - {import_tasks: tasks/vagrant.yml, tags: vagrant}
  - {import_tasks: tasks/virtualbox.yml, tags: virtualbox}
  - {import_tasks: tasks/yarn.yml, tags: yarn}
