---
- hosts: all
  connection: local
  become: yes
  vars:
  - docker_compose_version: 1.15.0
  - docker_machine_version: 0.12.2
  - intellij_version: 181.4892.42
  - intellij_version_name: 2018.1.3
  - intellij_checksum: "sha256:029c85ef39a6c2965fc98d9325c7d0e3120fda320e9137cee691b728470f0792"
  - intellij_archive: ideaIU-{{ intellij_version_name }}-no-jdk.tar.gz
  vars_files:
  - vars/secrets.yml

  handlers:
  - import_tasks: handlers/main.yml

  tasks:
  - {import_tasks: tasks/root-password.yml, tags: aws}
  - {import_tasks: tasks/aws-cli.yml, tags: aws}
  - {import_tasks: tasks/calibre.yml, tags: calibre}
  - {import_tasks: tasks/charles-proxy.yml, tags: [charles-proxy, charles]}
  - {import_tasks: tasks/compilers.yml, tags: [compilers, codekvast]}
  - {import_tasks: tasks/docker.yml, tags: [docker, codekvast]}
  - {import_tasks: tasks/fish.yml, tags: [fish, sdkman]}
  - {import_tasks: tasks/google-chrome.yml, tags: [chrome, google-chrome]}
  - {import_tasks: tasks/heroku-toolbelt.yml, tags: [heroku, codekvast]}
  - {import_tasks: tasks/intellij.yml, tags: [intellij, idea, codekvast]}
  - {import_tasks: tasks/misc.yml, tags: misc}
  - {import_tasks: tasks/nfs-mounts.yml, tags: [fstab, nfs, nfs-mounts]}
  - {import_tasks: tasks/scala.yml, tags: [compilers, scala]}
  - {import_tasks: tasks/spotify.yml, tags: spotify}
  - {import_tasks: tasks/vagrant.yml, tags: vagrant}
  - {import_tasks: tasks/virtualbox.yml, tags: virtualbox}
  - {import_tasks: tasks/yarn.yml, tags: yarn}
