---
- hosts: all
  connection: local
  become: yes
  vars:
  - docker_compose_version: 1.10.0
  - docker_machine_version: 0.9.0
  - intellij_version: 171.2613.7
  - intellij_checksum: "sha256:fe0f41dcf19769ffb070d079177fc775259fd75a1804fa9e9356d7bcb7765194"
  - intellij_archive: ideaIU-171.2613.7-no-jdk.tar.gz

  vars_files:
  - vars/secrets.yml

  handlers:
  - include: handlers/main.yml

  roles:
  - {role: franklinkim.docker, tags: [docker, docker-engine]}
  
  post_tasks:
  - {include: tasks/aws-cli.yml, tags: aws}
  - {include: tasks/calibre.yml, tags: calibre}
  - {include: tasks/compilers.yml, tags: [compilers, codekvast]}
  - {include: tasks/docker.yml, tags: [docker, codekvast]}
  - {include: tasks/fish.yml, tags: [fish, sdkman]}
  - {include: tasks/heroku-toolbelt.yml, tags: [heroku, codekvast]}
  - {include: tasks/intellij.yml, tags: [intellij, codekvast]}
  - {include: tasks/misc.yml, tags: misc}
  - {include: tasks/nfs-mounts.yml, tags: [fstab, nfs, nfs-mounts]}
  - {include: tasks/vagrant.yml, tags: vagrant}
  - {include: tasks/virtualbox.yml, tags: virtualbox}
